### ISSUE TITLE
weird upvote/downvote behaviour

### ISSUE THREAD

**Issue by marquestye** [mcmc101001/Orbital2023#87]
Sort by highest/lowest rating. Voting on items sometimes also reflects on other items. Seems to occur when the new vote affects the order of the list. Issue seems to be purely visual, votes are correct after refreshing the page.

**Comment by mcmc101001** [comment]
can attach screenshots and steps to recreate

**Comment by marquestye** [comment]
Sorted by highest rating:

![Image](https://github.com/mcmc101001/Orbital2023/assets/97437396/049b556e-9150-4c59-bd4f-35dd4a5c8213)

After upvoting the second item:

![Image](https://github.com/mcmc101001/Orbital2023/assets/97437396/2fb2b715-5574-45f2-a800-397b50baebf3)

**Comment by mcmc101001** [comment]
ok fixing now, seems like react is lost fetching data and rerendering

**Comment by mcmc101001** [comment]
# Solved

Problem was everytime a vote was issued, it triggers a rerender of the component, refetching data and moving the resource items around, causing react to mix up the old vs new components. This was done in order to sync background vote with current vote, but that can be solved more properly by having both rating components use same state to sync up their visual

**Comment by mcmc101001** [comment]
used jotai for state management to sync up state between the two
